---
driver:
  name: docker

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.16.4
  solo.rb:
    environment: aws-us-west-2-staging

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: ami-3be3f20b
    transport:
      username: ubuntu
  - name: centos-6.4
    driver:
      name: ec2
      region: us-west-2
      aws_ssh_key_id: shared-bootstrap
      instance_type: m2.xlarge
      subnet_id: subnet-3050df55
      security_group_ids: ["sg-f8ae169c"]
      image_id: ami-ccb753ff
      iam_profile_name: staging-metaflows-sensor-InstanceProfileObject-R8ZQ7XPIFWJS
      tags: 
        Name: metaflows-kitchen
    transport:
      username: metaflows
      ssh_key: ~/.ssh/shared-bootstrap

suites:
  - name: sensor
    user: metaflows
    run_list:
      - recipe[chef-metaflows::sensor]

  - name: agent
    run_list:
      - recipe[chef-metaflows::agent]
    attributes: { sensor_ip: "10.110.38.249" }
