---
driver:
  name: ec2

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: ami-3606c456
    transport:
      username: ubuntu
  - name: centos-6.4
    driver:
      name: ec2
      region: us-west-2
      aws_ssh_key_id: shared-bootstrap
      instance_type: m3.medium
      image_id: ami-c5cf03a5
      tags: 
        Name: metaflows-kitchen
    transport:
      username: metaflows
      ssh_key: ~/.ssh/shared-ssh-bootstrap

suites:
  - name: sensor
    user: metaflows
    run_list:
      - recipe[chef-metaflows::sensor]

  - name: agent
    run_list:
      - recipe[chef-metaflows::agent]
    attributes:
      metaflows:
        sensor_ip: 192.168.10.20
