driver:
  pull_platform_image: false
  chef_image: cincproject/cinc

provisioner:
  name: dokken
  product_name: cinc
  chef_binary: /opt/cinc/bin/cinc-client

transport:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: ubuntu-20.04-fips-chef-17
    driver:
      chef_version: 17
      image: repository.socrata/base-focal-fips
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN rm -f /usr/sbin/policy-rc.d
        - RUN DEBIAN_FRONTEND=noninteractive apt-get -y update
        - RUN DEBIAN_FRONTEND=noninteractive apt-get -y install systemd iproute2

suites:
  - name: agent
    runlist:
      - recipe[chef-metaflows::agent]
    attributes:
      metaflows:
        sensor_ip: 192.168.10.20
