name             'chef-metaflows'
maintainer       'Socrata, Inc.'
maintainer_email 'sysadmin@socrata.com'
license          'All rights reserved'
description      'Installs/Configures chef-metaflows'
long_description 'Installs/Configures chef-metaflows'
version          '0.5.1'

supports 'ubuntu'
supports 'centos'

depends 'rbenv'
depends 'runit'
depends 'socrata_configuration'
depends 'sshd'
depends 'yum-chef'
